# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: brookjs
subtitle: a streaming javascript framework
description:
author: James DiGioia
language: en
timezone: EST

# URL
url: http://valtech-nyc.github.io/brookjs/
root: /brookjs/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: index
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
    enable: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: documentation

deploy:
    type: git
    repo: git@github.com:valtech-nyc/brookjs.git
    branch: gh-pages
    message: "Docs updated {{ now('YYYY-MM-DD HH:mm:ss') }}"

prism_plugin:
    mode: preprocess
    theme: solarizedlight
